### PR TITLE
Integrate species filter with existing filter framework

### PR DESCRIPTION
**Pull request by RickMohr**
Filters:
* Add `AbstractChoiceFilter` as superclass of `OTMChoiceFilter` and new class `OTMSpeciesFilter`
* Move species logic from parent classes to `OTMSpeciesFilter`

Storyboard:
* In Filters panel, remove "Species" button (and "pushSpecies" segue) and expand filter view
* Species panel gets Storyboard ID of "SpeciesChooser" so we can launch it from code

Connects #274

### CODE REVIEW

**Comment by jwalgran** [comment]
I think this is an old bug that explains the why there was whitespace at the top of the filter list. If you search for a species, the species filter field scrolls offscreen and becomes inaccessible.

species-scrolls-offscreen

**Comment by jwalgran** [comment]
The discussion on #274 says the choice/species filters "... should advertise their clickability, using either a right-justified chevron or blue text"

Changing the label text color seems simpler, since it does not introduce the layout or text clipping issues that adding a chevron would.

**Comment by jwalgran** [comment]
This is a great refactor, and it functions well.

**Comment by RickMohr** [comment]
@jwalgran, ready for another look.

**Comment by jwalgran** [comment]
The fields get further an further apart each time I close and reopen the filter page

screen shot 2016-02-22 at 1 50 23 pm

I think the problem is with https://github.com/OpenTreeMap/otm-ios/pull/277/files#diff-cab00abd3e46f94d78ae11abd6c23006R888 

```objectivec
v.frame = CGRectOffset(v.frame, 0, yMax);
```

The frame on the view `v` is being expanded each time `initFiltersView` is called.

**Comment by RickMohr** [comment]
Sorry.... fixed.

**Comment by jwalgran** [comment]
Thanks for cleaning up that long standing header whitespace problem as part of this refactor

:+1:

**Pull request merged**
