### PR TITLE
Don't show a filter if user lacks permissions to read its field

### PR DESCRIPTION
**Pull request by RickMohr**
Also change Filters screen "Done" link to "Search"

Connects #275

### CODE REVIEW

**Comment by jwalgran** [comment]
Works well. Nice, small change.

If you have previously filtered the map, and want to revert to seeing all the features, having to tap "Search" after tapping "Clear" is a little strange. I think that is why we landed on the sub-optimal "Done" as a label. "Map" is another alternative, but I do not have strong feelings about it.

:+1:

**Comment by RickMohr** [comment]
Hm, I see what you mean. Another option would be "Apply".

**Comment by jwalgran** [comment]
"Apply" is also a little awkward in the empty case. "Search" is less technical and perhaps friendlier.

We could conditionally change the text of the button based on the state of the form, but I don't really see that behavior in other apps on the platform.

**Comment by RickMohr** [comment]
"Map" does connote taking you to the map, but it's not a verb.
"Show on Map" is possible...
I guess I'm inclined to stick with "Search".

**Comment by jwalgran** [comment]
:+1:

**Pull request merged**
